import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { ticketing_system_turn_pages } from "./ticketing-system-turn.pages.ts";
import { ticketing_system_turn_tables } from "./ticketing-system-turn.tables.ts";

export const ticketing_system_turn_module = define_module({
  resource: "ticketing-system-turn",
  labels: {
    singular: "Turnos de caja",
    plural: "Turnos de caja",
    read: "Ver Turnos de caja",
    write: "Editar Turnos de caja",
  },
  routes: define_crud({
    resource: "ticketing-system-turn",
    table: "ticketing_system_turn",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "ticketin",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      services: { type: "string", search: true },
      movements: { type: "number" },
      customer_type: { type: "string", search: true },
      assigned_box: { type: "string", search: true },
      status: { type: "string", search: true },
      priority_level: { type: "number" },
      time_box: { type: "json" },
      time_attending: { type: "json" },
      time: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: ticketing_system_turn_tables,
  pages: ticketing_system_turn_pages,
  menu: [
    {
      id: "turnos.ticketing-system-turn",
      label: "Turnos de caja",
      order: 0,
      pageId: "turnos.ticketing-system-turn",
      path: "ticketing-system-turn",
      permission: "subject.turnos.ticketing-system-turn.read",
      icon: "document",
    },
    {
      id: "turnos.ticketing-system-consecutive",
      label: "Consecutivos de turnos",
      order: 0,
      pageId: "turnos.ticketing-system-consecutive",
      path: "ticketing-system-consecutive",
      permission: "subject.turnos.ticketing-system-consecutive.read",
      icon: "document",
    },
    {
      id: "turnos.ticketing-system-box-config",
      label: "Configurar cajas",
      order: 0,
      pageId: "turnos.ticketing-system-box-config",
      path: "ticketing-system-box-config",
      permission: "subject.turnos.ticketing-system-box-config.read",
      icon: "document",
    },
    {
      id: "turnos.news-banner-control",
      label: "Control de banner de noticias",
      order: 0,
      pageId: "turnos.news-banner-control",
      path: "news-banner-control",
      permission: "subject.turnos.news-banner-control.read",
      icon: "document",
    },
    {
      id: "turnos.ticketing-system-service-type",
      label: "Servicios de caja",
      order: 0,
      pageId: "turnos.ticketing-system-service-type",
      path: "ticketing-system-service-type",
      permission: "subject.turnos.ticketing-system-service-type.read",
      icon: "document",
    },
    {
      id: "turnos.ticketing-system-customer-type",
      label: "Tipos de usuario",
      order: 0,
      pageId: "turnos.ticketing-system-customer-type",
      path: "ticketing-system-customer-type",
      permission: "subject.turnos.ticketing-system-customer-type.read",
      icon: "document",
    },
    {
      id: "turnos.ticketing-system-turn-youtube",
      label: "Youtube para turnos",
      order: 0,
      pageId: "turnos.ticketing-system-turn-youtube",
      path: "ticketing-system-turn-youtube",
      permission: "subject.turnos.ticketing-system-turn-youtube.read",
      icon: "document",
    },
    {
      id: "turnos.ticketing-system-priority",
      label: "Prioridades",
      order: 0,
      pageId: "turnos.ticketing-system-priority",
      path: "ticketing-system-priority",
      permission: "subject.turnos.ticketing-system-priority.read",
      icon: "document",
    }
    ],
});
